name: covid19
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  cupertino_icons: ^0.1.2
  shimmer: ^1.1.0
  pie_chart: ^3.1.1
  webview_flutter: ^0.3.19+9
  flutter_html: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: NavigationIcon
      fonts:
        - asset: assets/fonts/NavigationIcon.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
