export 'splash/splash_screen.dart';
export 'home/home_screen.dart';
export 'info/info_screen.dart';
export 'news/news_screen.dart';
export 'contact/contact_screen.dart';
export 'main/main_screen.dart';
export 'statistic/statistic_screen.dart';
export 'webview/webview_screen.dart';
export 'news/news_detail_screen.dart';